---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trow-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - host: trow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trow-svc
                port:
                  name: http-tcp
  tls:
    - hosts:
        - trow.local
      secretName: trow
---
apiVersion: v1
kind: Service
metadata:
  name: trow-svc
spec:
  selector:
    app: trow
  type: NodePort
  ports:
    - name: http-tcp
      protocol: TCP
      port: 8000
      targetPort: trow-http-port
    - name: https-tcp
      protocol: TCP
      port: 8443
      targetPort: trow-https-port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trow
spec:
  selector:
    matchLabels:
      app: trow
  serviceName: trow
  template:
    metadata:
      labels:
        app: trow
    spec:
      containers:
        - name: trow-pod
          image: containersol/trow:0.3
          args:
            - "--no-tls"
            - "-n"
            - "trow.local"
          imagePullPolicy: Always
          ports:
            - name: trow-http-port
              containerPort: 8000
            - name: trow-https-port
              containerPort: 8443
          volumeMounts:
            - name: data-vol
              mountPath: /data
      securityContext:
        runAsUser: 333333
        runAsGroup: 333333
        fsGroup: 333333
      dnsConfig:
        searches:
          - trow.local
  volumeClaimTemplates:
    - metadata:
        name: data-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
