apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: titanic-pvc
  namespace: titanic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
